### ISSUE TITLE
Boot Strap Model Show broken.

### ISSUE THREAD

**Issue by chaoscode** [ExactTarget/fuelux#1294]
When using your JS file www.fuelcdn.com/fuelux/3.6.3/js/fuelux.min.js

When I do a show modal now all I get is a greyed out uninteractionable version of the model and if I click on it , it closes. If i remove your JS. it works fine. Help.

**Comment by interactivellama** [comment]
Is this modal working for you? It's using Bootstrap 3.3.4 and Fuel UX 3.7.1. 

http://fuelux-mctheme.herokuapp.com/examples/bootstrap-javascript/bootstrap-javascript.html

**Comment by chaoscode** [comment]
Yes, it does work for me but I am showing my modal from the javascript as I need to do some behind the scenes work before it shows.

**Comment by interactivellama** [comment]
Can you JSfiddle it, please?

Or here's [a Codepen](http://codepen.io/anon/pen/QbNvGp), I already have set up.

**Comment by chaoscode** [comment]
Its a little complex, I couldnt load it in JSFiddle but I have skype and I can share my screen. Reason it wouldnt work in JSFiddle is becuase its a ADDIN for a gps company API site.

**Comment by interactivellama** [comment]
It would be nice to see it isolated to know that it's a Fuel UX bug and not another library that's blocking it.

**Comment by chaoscode** [comment]
Done 

http://codepen.io/anon/pen/QbNvGp

Press the Lookup Vehicle button.

**Comment by interactivellama** [comment]
I removed the Fuel UX JS and CSS from it, and it's still broken. I'm pretty it has something to do with the z-index of your modal and your "background div", but this does not appear to be a Fuel UX though.

http://codepen.io/anon/pen/XbdRZP

**Comment by interactivellama** [comment]
Unless you can figure out that Fuel UX is causing this CSS problem, I'm going to close this issue. I hope thinks worked out!
